//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopee_Autobuy_Bot.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ProductLinkMalaysia {
            get {
                return ((string)(this["ProductLinkMalaysia"]));
            }
            set {
                this["ProductLinkMalaysia"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CountdownMode {
            get {
                return ((bool)(this["CountdownMode"]));
            }
            set {
                this["CountdownMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CountdownHour {
            get {
                return ((int)(this["CountdownHour"]));
            }
            set {
                this["CountdownHour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CountdownMinutes {
            get {
                return ((int)(this["CountdownMinutes"]));
            }
            set {
                this["CountdownMinutes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string CountdownMicroSeconds {
            get {
                return ((string)(this["CountdownMicroSeconds"]));
            }
            set {
                this["CountdownMicroSeconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PaymentMethod {
            get {
                return ((string)(this["PaymentMethod"]));
            }
            set {
                this["PaymentMethod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WalletPin {
            get {
                return ((string)(this["WalletPin"]));
            }
            set {
                this["WalletPin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Courier {
            get {
                return ((string)(this["Courier"]));
            }
            set {
                this["Courier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VariationCheck {
            get {
                return ((bool)(this["VariationCheck"]));
            }
            set {
                this["VariationCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string VariationString {
            get {
                return ((string)(this["VariationString"]));
            }
            set {
                this["VariationString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ProductQuantity {
            get {
                return ((int)(this["ProductQuantity"]));
            }
            set {
                this["ProductQuantity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DisableImageExtension {
            get {
                return ((bool)(this["DisableImageExtension"]));
            }
            set {
                this["DisableImageExtension"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CourierCheck {
            get {
                return ((bool)(this["CourierCheck"]));
            }
            set {
                this["CourierCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Website {
            get {
                return ((string)(this["Website"]));
            }
            set {
                this["Website"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BankType {
            get {
                return ((string)(this["BankType"]));
            }
            set {
                this["BankType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ShopeePayPin {
            get {
                return ((string)(this["ShopeePayPin"]));
            }
            set {
                this["ShopeePayPin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int TimeOut {
            get {
                return ((int)(this["TimeOut"]));
            }
            set {
                this["TimeOut"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RedeemCoin {
            get {
                return ((bool)(this["RedeemCoin"]));
            }
            set {
                this["RedeemCoin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PlaySound {
            get {
                return ((bool)(this["PlaySound"]));
            }
            set {
                this["PlaySound"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Headless {
            get {
                return ((bool)(this["Headless"]));
            }
            set {
                this["Headless"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Refresh {
            get {
                return ((bool)(this["Refresh"]));
            }
            set {
                this["Refresh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FlashSaleMode {
            get {
                return ((bool)(this["FlashSaleMode"]));
            }
            set {
                this["FlashSaleMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ID {
            get {
                return ((string)(this["ID"]));
            }
            set {
                this["ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int RefreshSeconds {
            get {
                return ((int)(this["RefreshSeconds"]));
            }
            set {
                this["RefreshSeconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Logging {
            get {
                return ((bool)(this["Logging"]));
            }
            set {
                this["Logging"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CountdownSeconds {
            get {
                return ((int)(this["CountdownSeconds"]));
            }
            set {
                this["CountdownSeconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TestMode {
            get {
                return ((bool)(this["TestMode"]));
            }
            set {
                this["TestMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CardLast4Digit {
            get {
                return ((string)(this["CardLast4Digit"]));
            }
            set {
                this["CardLast4Digit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RedeemShopeeVoucher {
            get {
                return ((bool)(this["RedeemShopeeVoucher"]));
            }
            set {
                this["RedeemShopeeVoucher"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ClaimShopVoucher {
            get {
                return ((bool)(this["ClaimShopVoucher"]));
            }
            set {
                this["ClaimShopVoucher"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BuyMode {
            get {
                return ((string)(this["BuyMode"]));
            }
            set {
                this["BuyMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BelowSpecificPrice {
            get {
                return ((string)(this["BelowSpecificPrice"]));
            }
            set {
                this["BelowSpecificPrice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BelowSpecificPriceCheckout {
            get {
                return ((string)(this["BelowSpecificPriceCheckout"]));
            }
            set {
                this["BelowSpecificPriceCheckout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ScheduleBot {
            get {
                return ((bool)(this["ScheduleBot"]));
            }
            set {
                this["ScheduleBot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ScheduleBotTomorrow {
            get {
                return ((bool)(this["ScheduleBotTomorrow"]));
            }
            set {
                this["ScheduleBotTomorrow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DontShowThisAgain {
            get {
                return ((bool)(this["DontShowThisAgain"]));
            }
            set {
                this["DontShowThisAgain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DontShowThisAgainTipsPrompt {
            get {
                return ((bool)(this["DontShowThisAgainTipsPrompt"]));
            }
            set {
                this["DontShowThisAgainTipsPrompt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowTipsPromptDontShowThisAgain {
            get {
                return ((bool)(this["ShowTipsPromptDontShowThisAgain"]));
            }
            set {
                this["ShowTipsPromptDontShowThisAgain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ShopeeRegion {
            get {
                return ((string)(this["ShopeeRegion"]));
            }
            set {
                this["ShopeeRegion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ProductLinkSingapore {
            get {
                return ((string)(this["ProductLinkSingapore"]));
            }
            set {
                this["ProductLinkSingapore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ProductLinkThailand {
            get {
                return ((string)(this["ProductLinkThailand"]));
            }
            set {
                this["ProductLinkThailand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//button[contains(@class, \'btn-solid-primary\') and contains(text(), \'buy now\')]")]
        public string product_strBuyNowButton {
            get {
                return ((string)(this["product_strBuyNowButton"]));
            }
            set {
                this["product_strBuyNowButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//div[contains(@class, \'flex items-center TvGNLb\')]")]
        public string product_strProductVariationFlexBox {
            get {
                return ((string)(this["product_strProductVariationFlexBox"]));
            }
            set {
                this["product_strProductVariationFlexBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//input[contains(@class, \'_14flVw z4c5Da\')]")]
        public string product_strQuantityTextBox {
            get {
                return ((string)(this["product_strQuantityTextBox"]));
            }
            set {
                this["product_strQuantityTextBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//div[contains(@class, \'pmmxKx\')]")]
        public string product_strCurrentProductPrice {
            get {
                return ((string)(this["product_strCurrentProductPrice"]));
            }
            set {
                this["product_strCurrentProductPrice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//div[contains(@class, \'SwrRMG\')]")]
        public string product_strSaleBanner {
            get {
                return ((string)(this["product_strSaleBanner"]));
            }
            set {
                this["product_strSaleBanner"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//*[@id=\"main\"]/div/div[2]/div[1]/div/div[3]/div[2]/div[7]/button[4]")]
        public string cart_strCheckOut {
            get {
                return ((string)(this["cart_strCheckOut"]));
            }
            set {
                this["cart_strCheckOut"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//*[@id=\"main\"]/div/div[2]/div/div/div[3]/div[2]/div[7]/div[1]/label/div")]
        public string cart_strSelectAllCheckbox {
            get {
                return ((string)(this["cart_strSelectAllCheckbox"]));
            }
            set {
                this["cart_strSelectAllCheckbox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//span[@class=\'_1CXksa\']")]
        public string cart_strProductPriceLabel {
            get {
                return ((string)(this["cart_strProductPriceLabel"]));
            }
            set {
                this["cart_strProductPriceLabel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//button[contains(@class, \'btn\') and contains(text(), \'Claim\')]")]
        public string cart_strClaimShopVC {
            get {
                return ((string)(this["cart_strClaimShopVC"]));
            }
            set {
                this["cart_strClaimShopVC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//div[contains(@class, \'xkMOGx\') and contains(text(), \'Your shopping cart is empt" +
            "y\')]")]
        public string cart_strCartEmptyLabel {
            get {
                return ((string)(this["cart_strCartEmptyLabel"]));
            }
            set {
                this["cart_strCartEmptyLabel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//button[contains(@class, \'stardust-button\') and contains(text(), \'Place Order\')]" +
            "")]
        public string checkout_strPlaceOrder {
            get {
                return ((string)(this["checkout_strPlaceOrder"]));
            }
            set {
                this["checkout_strPlaceOrder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//button[contains(@class, \'_6dwQij\') and contains(text(), \'Select Voucher\')]")]
        public string chekcout_strClaimShopeeVcButton {
            get {
                return ((string)(this["chekcout_strClaimShopeeVcButton"]));
            }
            set {
                this["chekcout_strClaimShopeeVcButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//div[contains(@class, \'qa9DDd U0bjBP VK0V4t\')]")]
        public string checkout_strShopeeVcContainer {
            get {
                return ((string)(this["checkout_strShopeeVcContainer"]));
            }
            set {
                this["checkout_strShopeeVcContainer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//button[contains(@class, \'btn\') and contains(text(), \'OK\')]")]
        public string checkout_strShopeeVcOkButton {
            get {
                return ((string)(this["checkout_strShopeeVcOkButton"]));
            }
            set {
                this["checkout_strShopeeVcOkButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//*[@id=\"main\"]/div/div[2]/div[2]/div[3]/div[2]/div[2]/label")]
        public string checkout_strRedeemCoinCheckbox {
            get {
                return ((string)(this["checkout_strRedeemCoinCheckbox"]));
            }
            set {
                this["checkout_strRedeemCoinCheckbox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//div[contains(@class, \'_1n5Ut6\') and contains(text(), \'change\')]")]
        public string checkout_strChangePaymentButton {
            get {
                return ((string)(this["checkout_strChangePaymentButton"]));
            }
            set {
                this["checkout_strChangePaymentButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Font windowsFont {
            get {
                return ((global::System.Drawing.Font)(this["windowsFont"]));
            }
            set {
                this["windowsFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection chromeProfileList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["chromeProfileList"]));
            }
            set {
                this["chromeProfileList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string chromeProfile {
            get {
                return ((string)(this["chromeProfile"]));
            }
            set {
                this["chromeProfile"] = value;
            }
        }
    }
}
